fix rust rtfm `base_url`
Cryptex-github/bobo-bot pull request #39
Opened 2022-05-03 21:02 UTC by Tom-the-Bomb

!!!!!!!!

2022-05-03 21:12 UTC, jay3332 commented
💣

2022-05-03 21:26 UTC, Cryptex-github requested changes

2022-05-03 21:26 UTC, Cryptex-github commented on cogs/rtfm.py
> +        base_url = 'https://doc.rust-lang.org'
Tom bomb this will break fetch tom bomb see L175

2022-05-05 00:15 UTC, Cryptex-github commented
Fixed in commit d7c6c25f709167dcec48820bdf390b4dca26a271

2022-05-05 00:15 UTC, closed without merging

2022-05-05 18:05 UTC, Tom-the-Bomb commented
thou have not fixed the regex grammar